#!/bin/sh
#inkVerbBoss! verb.ink

# This installs Vrk Desktop settings, theming, and Vrk Wallpaper
## Prerequesite: Vrk™ must be installed

# How to use:
## sudo install-vrk-desktop

# Eg: (re-install for specific desktop)
## sudo install-vrk-desktop $DESKTOP_SESSION


# Set user
VRK_USER=${SUDO_USER}

# Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22; fi

# Include the config
. /opt/vrk/machineinfo

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-vrk-desktop
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-vrk-desktop
"
exit 22; fi

# Check if Vrk Desktop installed
if [ "${VRK_DESKTOP_INSTALLED}" = "YES" ]; then
echo "Vrk desktop apps already installed."
## Allow re-install per desktop
 if [ -n "$1" ]; then
 echo "If you would like to re-install it for a specific desktop, type \"yes\"..."
 read QYN
  if [ "$QYN" != "yes" ]; then
  echo "I quit."
  exit 0
  fi
 else
 exit 0
 fi
fi

# Check if Vrk Desktop installed (again)
if [ -f /opt/vrk/.vrk-desktop-installed ]; then
echo "Vrk Desktop already installed on this machine."
exit 0; fi

# Distro version
ubuntu_release=$(lsb_release -r -s)

# Change the Distro variable if re-installing per-desktop
if [ -n "$1" ]; then
LINUX_DESKTOP="$1"; fi



# Global

# Add repos
/opt/vrk/boss/install-repos

# Update & Upgrade
#update included in install-repos
#apt update -y --fix-missing
apt upgrade -y --fix-missing
apt install -yf
apt update -y --fix-missing

# Basic apps: Gedit, Guake, Docky, Chromium, Thunderbird, Firefox, Rhythmbox, Vino, WordGrinder (Desktop Sharing settings)
chkfile=/opt/vrk/.inst-dsktp-0
if [ ! -f "$chkfile" ]; then
apt install -y ttf-mscorefonts-installer
apt install -y jackd2
apt install -y gedit tilda docky chromium-browser djview-plugin thunderbird firefox rhythmbox vino wordgrinder-ncurses
#if [ "${LINUX_DESKTOP}" = "ubuntu" ]; then
#apt install -y unity-chromium-extension #NO! This made the 64bit ASUS run both Chrome and Chromium too slowly!
#fi

# Adapta
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dsktp-1
if [ ! -f "$chkfile" ]; then
/opt/vrk/boss/install-adapta

# Gedit Themes
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dsktp-2
if [ ! -f "$chkfile" ]; then
/opt/vrk/boss/install-geditthemes

# Ubuntu Studio Wallpapers, GTK configs, Variety
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dsktp-3
if [ ! -f "$chkfile" ]; then
apt install -y conky conky-all ubuntustudio-wallpapers gnome-terminal variety htop
#apt install -y gtk-theme-config # As of 18.04 this does not work

# LibreOffice (done now for vrk-desktop settings dependencies)
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dsktp-4
if [ ! -f "$chkfile" ]; then
apt install -y libreoffice-writer libreoffice-calc

# Git, build tools, and theme dependencies (may be redundant, but never can be too sure, here they all are from each theme's dependency instructions)
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dsktp-5
if [ ! -f "$chkfile" ]; then
apt install -y git build-essential dconf-cli autoconf automake libtool intltool inkscape cmake krita gimp
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dsktp-6
if [ ! -f "$chkfile" ]; then
apt install -y gnome-themes-standard libgdk-pixbuf2.0-dev libglib2.0-dev libgtk-3-dev libxml2-utils gtk3-engines-unico gtk2-engines-murrine gtk2-engines-pixbuf pkg-config python3 ruby-bundler ruby-sass
## Specific for making Adapta themes (may only be used to make Adapta, but why not)
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dsktp-7
if [ ! -f "$chkfile" ]; then
apt install -y libsass0 librsvg2-dev
#apt install -y gdk-pixbuf2-devel glib2-devel librsvg2-devel libsass libxml2 pkgconfig cutomake sassc # not installing
#/opt/vrk/boss/install-libsassc # not installing

# Icon theme for LibreOffice
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dsktp-8
if [ ! -f "$chkfile" ]; then
apt install -y libreoffice-style-sifr libreoffice-style-galaxy libreoffice-style-hicontrast libreoffice-style-human libreoffice-style-oxygen libreoffice-style-tango

# Wallpapers
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dsktp-9
if [ ! -f "$chkfile" ]; then
/opt/vrk/boss/install-vrk-vallpaper

# Themes
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dsktp-10
if [ ! -f "$chkfile" ]; then
/opt/vrk/boss/themicons-git-upstall
touch $chkfile; fi

# Global #

# Unity 16.04
if [ "${LINUX_DESKTOP}" = "ubuntu" ] && [ "$ubuntu_release" = "16.04" ]; then
#/opt/vrk/donjon/vrk-unity-notifications-off # replaced by the tool below
add-apt-repository -y ppa:vlijm/nonotifs
apt update -y --fix-missing
chkfile=/opt/vrk/.inst-dsktp-11
if [ ! -f "$chkfile" ]; then
apt install -y unity-tweak-tool nonotifs
touch $chkfile; fi
fi
# Unity 16.04 #

# Ubuntu (GNOME)
if [ "${LINUX_DESKTOP}" = "ubuntu" ] || [ "$LINUX_DESKTOP" = "ubuntu-wayland" ]; then

chkfile=/opt/vrk/.inst-dsktp-12
if [ ! -f "$chkfile" ]; then
apt install -y gnome-tweak-tool
touch $chkfile; fi
fi
# GNOME #

# GNOME
if [ "${LINUX_DESKTOP}" = "gnome" ]; then
chkfile=/opt/vrk/.inst-dsktp-13
if [ ! -f "$chkfile" ]; then
apt install -y gnome-tweak-tool
touch $chkfile; fi
fi
# GNOME #

# Xubuntu/UbuntuStudio
if [ "${LINUX_DESKTOP}" = "xubuntu" ] || [ "${LINUX_DESKTOP}" = "ubuntustudio" ] ; then
## xfDashboard
#NO LONGER IN TESTING, normal repos may work, just in case
add-apt-repository -y ppa:xubuntu-dev/extras
apt update -y --fix-missing
chkfile=/opt/vrk/.inst-dsktp-14
if [ ! -f "$chkfile" ]; then
apt install -y xfdashboard
touch $chkfile; fi
fi
# Xubuntu #


# KDE
#if [ "$LINUX_DESKTOP" = "/usr/share/xsessions/plasma" ]; then

#fi
# KDE #


# MATE
#if [ "$LINUX_DESKTOP" = "mate" ]; then

#fi
# MATE #


# Cinnamon
#if [ "$LINUX_DESKTOP" = "cinnamon" ]; then

#fi
# Cinnamon #


# Mint_XFCE
#if  [ "${LINUX_DESKTOP}" = "xfce" ]; then

#fi
# Mint_Xfce

# Arch
#if  [ "${LINUX_DESKTOP}" = "arch" ]; then

#pacman -S gtk-engine-murrine gtk-engines
#pacman -S gtk-engine-murrine gtk-engines

#fi
# Arch

# Set the system browser default for x-www-browser (not same as Application Defaults)
echo 'auto
/usr/bin/x-www-browser

/usr/bin/firefox
40
' > /var/lib/dpkg/alternatives/x-www-browser

# Remove every $chkfile
rm /opt/vrk/.inst-dsktp-*

# Set configs
echo "VRK_DESKTOP_INSTALLED=\"YES\"" >> /opt/vrk/machineinfo
touch /opt/vrk/.vrk-desktop-installed

# Touch LibreOffice configs
echo "
Launching LibreOffice quick, if it doesn't cloes automatically, just close it yourself...
"
## Add the ampersand to the end of the line so that the desktop app doesn't lock the terminal
libreoffice &
## Wait for the LibreOffice script to finish
sleep 1
## Kill the name of the "splash screen" process that eventually ends up running
killall oosplash
## Own the config files just made
chown -R ${VRK_USER}:${VRK_USER} /home/${VRK_USER}/.config/libreoffice
# Cleanup
apt autoremove -y

# Finish
echo "Vrk Desktop is now installed. Now you can run set-vrk-desktop"
sleep 2
