#!/bin/sh
#inkVerbSurfer! verb.ink

# This sets the Vubuntu Desktop preferences for a Vubuntu installation.
## Prerequesite: Vrk™ must be installed

## To observe terminal commands that create these settings while using GUI: dconf watch /

# How to use:
## set-vrk-desktop

# Eg: (re-install for specific desktop)
## set-vrk-desktop $DESKTOP_SESSION


# Set
## Vall room
VALL_ROOM="vrk"
## Vall background
VALL_BACKGRND="Get-to-Vrk.png"
## Vall lockscreen
VALL_LOCKSRN="Vrk-Mesh-Disk.png"

# Check to make sure this not run as sudo or root
if [ "$(id -u)" = "0" ]; then
echo "Do not run as root or sudo."; exit 22
fi

# Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check if Vrk installed to user
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "First, run install-vrk for this user. See README.md"; exit 22
fi

# Check if Vrk Desktop is already set for this user
. ~/.vrk/configs/stationinfo
if [ "${VRK_DESKTOP_SET}" = "YES" ]; then
echo "Vrk Desktop already set for this user.

Type \"yes\" to run it again, anything else to quit...
"
read YESRESET
 if [ "${YESRESET}" != "yes" ]; then
exit 0
 fi
fi

# Include the config
. /opt/vrk/machineinfo

# Change the Distro variable if re-installing per-desktop
if [ -n "$1" ]; then
LINUX_DESKTOP="$1"; fi


# Distro version
ubuntu_release=$(lsb_release -r -s)
## Depreciated
if [ "$ubuntu_release" = "14.04" ] || [ "$ubuntu_release" = "12.04" ]; then
echo "Verion $ubuntu_release not supported."
exit 77; fi

# Global exceptions tests
#if [ "$LINUX_DESKTOP" = "gnome" ]; then
#DESKTOP_GLOBE="EXCEPTION"; fi
if [ "$LINUX_DESKTOP" = "/usr/share/xsessions/plasma" ]; then
DESKTOP_GLOBE="EXCEPTION"; fi
if [ "$LINUX_DESKTOP" = "xfce" ]; then
DESKTOP_GLOBE="EXCEPTION"; fi

# Global

## Templatesq
~/.vrk/boards/do-vrktemplates

## Gedit (may be redundant in per-environments below, but just be safe)
gsettings set org.gnome.gedit.preferences.editor wrap-mode none
gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
gsettings set org.gnome.gedit.preferences.editor display-overview-map true
gsettings set org.gnome.gedit.preferences.editor highlight-current-line true
gsettings set org.gnome.gedit.preferences.editor bracket-matching true
gsettings set org.gnome.gedit.preferences.editor scheme 'solarized-dark'

# Setup Vim for copy to clipboard
echo 'nnoremap <C-c> "+y
vnoremap <C-c> "+y
nnoremap <C-p> "+p
vnoremap <C-p> "+p
syntax on' > ~/.vimrc


## Pause to avoid trouble
sleep 1

# Global #

# GNOME
if [ "$LINUX_DESKTOP" = "gnome" ]; then

# Desktop
dconf write /org/gnome/desktop/input-sources/xkb-options "['compose:caps']"
gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true
gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier '<Alt>'
gsettings set org.gnome.desktop.wm.preferences action-middle-click-titlebar 'minimize'
gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,close'
gsettings set org.gnome.desktop.screensaver lock-enabled false
gsettings set org.gnome.desktop.wm.preferences focus-new-windows 'smart'
gsettings set org.gnome.desktop.interface clock-show-weekday true
gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface toolbar-detachable false
gsettings set org.gnome.desktop.notifications show-banners false
gsettings set org.gnome.desktop.notifications show-in-lock-screen false
gsettings set org.gnome.desktop.session idle-delay "uint32 0"
gsettings set org.gnome.desktop.interface gtk-theme "Matcha-dark-sea"

## Hotkeys for apps
### X: Gedit teXt editor
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ command 'gedit'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ name 'Editor'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ binding '<Super>x'
wait
### E: Files
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ command 'nautilus'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ name 'Files'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ binding '<Super>e'
wait
### Q: Calculator
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ command 'gnome-calculator'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ name 'Calculator'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ binding '<Super>q'
wait
### Apply the settings
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/','/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/','/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/']"
wait

fi

# GNOME #

# Xfce
## Help:
#http://docs.xfce.org/xfce/xfconf/xfconf-query

if [ "${LINUX_DESKTOP}" = "xfce" ] ; then

## App Defaults
cp -f ~/.vrk/donjon/global/config/mimeapps.list ~/.config/

## Autostart special
cp -rf ~/.vrk/donjon/xfce/config/autostart ~/.config/

## Mouse cursor theme
gsettings set org.gnome.desktop.interface cursor-theme "DMZ-Black"

## Gedit
gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
gsettings set org.gnome.gedit.preferences.editor scheme 'atom-one'

## Compose Key: CapLock key
xfconf-query -n -c keyboard-layout -p /Default/XkbOptions/Compose -t string -s "compose:caps"
#xfconf-query -n -c keyboard-layout -p /Default/XkbOptions/Compose -t string -s "compose:menu"

## Set theme & icons
### Window Theme
xfconf-query -c xfwm4 -p /general/theme -s "Numix"
### Color Theme
xfconf-query -c xsettings -p /Net/ThemeName -s "Adapta-Nokto"
### Per distro ;-)
if [ "${LINUX_DESKTOP}" = "ubuntustudio" ]; then
xfconf-query -c xsettings -p /Net/IconThemeName -s "Surfn-Arch-Blue"; fi
if [ "${LINUX_DESKTOP}" = "xubuntu" ]; then
xfconf-query -c xsettings -p /Net/IconThemeName -s "Surfn-Numix-Misty"; fi

## Pause to avoid trouble
sleep 1

## Whisker menu
### Icon
if [ "${LINUX_DESKTOP}" = "xfce" ]; then
sed -i "s/button-icon=.*/button-icon=\/var\/local\/vall\/rooms\/vubuntu\/icons\/inkVerb-disk-white\.svg/g" ~/.config/xfce4/panel/whiskermenu-1.rc; fi
#### Show it
sed -i "s/show-button-icon=.*/show-button-icon=true/g" ~/.config/xfce4/panel/whiskermenu-1.rc
### Favorites
sed -i "s/favorites=.*/favorites=exo-file-manager\.desktop,vivaldi-stable\.desktop,google-chrome\.desktop,chromium-browser\.desktop,firefox\.desktop,gedit\.desktop,libreoffice-writer\.desktop,thunderbird\.desktop,rhythmbox\.desktop,org\.gnome\.Software\.desktop,gnome-calculator\.desktop/g" ~/.config/xfce4/panel/whiskermenu-1.rc
sed -i "s/favorites-in-recent=.*/favorites-in-recent=false/g" ~/.config/xfce4/panel/whiskermenu-1.rc

## Terminal color scheme
### Check if done
if [ ! -f "~/.vrk/configs/.xt-xfce" ]; then
### Add the theme
~/.vrk/donjon/xt-xfce
### Make the record
touch ~/.vrk/configs/.xt-xfce
fi

## Workspaces & windows
xfconf-query -c xfwm4 -p /general/workspace_count -s 3
xfconf-query -c xfwm4 -p /general/scroll_workspaces -s true
xfconf-query -c xfwm4 -p /general/mousewheel_rollup -s true
xfconf-query -c xfwm4 -p /general/tile_on_move -s true

## Wallpaper
#first one already set by set-vall, but let's spice up the rest, shall we...
#xfconf-query -n -t string -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s /usr/share/xfce4/backdrops/inkPage.png
xfconf-query -n -t string -c xfce4-desktop -p /backdrop/screen0/monitor1/workspace0/last-image -s /usr/share/xfce4/backdrops/Pen-Black.png
xfconf-query -n -t string -c xfce4-desktop -p /backdrop/screen0/monitor2/workspace0/last-image -s /usr/share/xfce4/backdrops/Whitetype-Ink-Gray.png
xfconf-query -n -t string -c xfce4-desktop -p /backdrop/screen0/monitor3/workspace0/last-image -s /usr/share/xfce4/backdrops/inkCorner.png

## Pause to avoid trouble
sleep 1

## Hot keys
### Whisker menu
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/Super_L" -t string -s 'xfce4-popup-whiskermenu'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/Super_R" -t string -s 'xfce4-popup-whiskermenu'
#can't use <Super> given the above Super_L and Super_R declarations :-(
#xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>z" -t string -s 'xfce4-popup-whiskermenu'
#xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>space" -t string -s 'xfce4-popup-whiskermenu'
### Xfdashboard
#### set for both orders since order matters
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Ctrl><Alt>Super_L" -t string -s 'xfdashboard'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Ctrl><Alt>Super_R" -t string -s 'xfdashboard'
### Window tiling
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Ctrl><Super>Up" -t string -s 'tile_up_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Ctrl><Super>Down" -t string -s 'tile_down_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Ctrl><Super>Left" -t string -s 'tile_left_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Ctrl><Super>Right" -t string -s 'tile_right_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Shift><Super>Left" -t string -s 'tile_up_left_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Shift><Super>Right" -t string -s 'tile_up_right_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Alt><Super>Left" -t string -s 'tile_down_left_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Alt><Super>Right" -t string -s 'tile_down_right_key'
### Desktop apps
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>d" -t string -s 'gedit'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>e" -t string -s 'thunar'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>q" -t string -s 'gnome-calculator'

## Pause to avoid trouble
sleep 1

## Xfdashboard
###DEV see available options: xfconf-query -c xfdashboard -lv
#http://xfdashboard.froevel.de/settings.html
#https://github.com/gmc-holle/xfdashboard/issues/122
## Dashboard settings
xfconf-query -n -t bool -c xfdashboard -p /always-launch-new-instance -s false
xfconf-query -n -t bool -c xfdashboard -p /components/applications-view/show-all-apps -s true
xfconf-query -n -t bool -c xfdashboard -p /components/windows-view/scroll-event-changes-workspace -s true
xfconf-query -n -t string -c xfdashboard -p /theme -s xfdashboard-dark
## Enable the hot-corner plugin by adding the hot-corner value to enabled-plugins as a new property
xfconf-query -n -c xfdashboard -p /enabled-plugins -a -t string -s hot-corner
## Enable gnome shell search provider also (this resets all plugins every time)
#xfconf-query -n -c xfdashboard -p /enabled-plugins -a -t string -s hot-corner -t string -s gnome-shell-search-provider
## Settings for hotcorner
xfconf-query -n -t string -c xfdashboard -p /plugins/hot-corner/activation-corner -s XFDASHBOARD_HOT_CORNER_SETTINGS_ACTIVATION_CORNER_TOP_LEFT
xfconf-query -n -t string -c xfdashboard -p /plugins/hot-corner/activation-duration -s 27
xfconf-query -n -t string -c xfdashboard -p /plugins/hot-corner/activation-radius -s 1
## Favorites (spelled British in settings!)
### Defaults:
### xfconf-query -n -t string -c xfdashboard -p /favourites -t string -s "exo-web-browser.desktop" -t string -s "exo-mail-reader.desktop" -t string -s "exo-file-manager.desktop" -t string -s "exo-terminal-emulator.desktop"
### xfconf-query -n -t string -c xfdashboard -p /favourites -t string -s "exo-file-manager.desktop" -t string -s "chromium-browser.desktop" -t string -s "firefox.desktop" -t string -s "thunderbird.desktop" -t string -s "gedit.desktop" -t string -s "libreoffice-writer.desktop" -t string -s "gnome-calculator.desktop" -t string -s "xfce4-settings-manager.desktop"
### xfconf-query -n -c xfdashboard -p /favourites -t string -s "exo-file-manager.desktop" -t string -s "exo-web-browser.desktop" -t string -s "exo-mail-reader.desktop" -t string -s "gedit.desktop" -t string -s "libreoffice-writer.desktop" -t string -s "gnome-calculator.desktop" -t string -s "xfce4-settings-manager.desktop"
### xfconf-query -n -c xfdashboard -p /favourites -t string -s "exo-file-manager.desktop" -t string -s "chromium-browser.desktop" -t string -s "firefox.desktop" -t string -s "thunderbird.desktop" -t string -s "gedit.desktop" -t string -s "libreoffice-writer.desktop" -t string -s "gnome-calculator.desktop" -t string -s "xfce4-settings-manager.desktop"
~/.vrk/donjon/xfdashboard-zilla

## App Theming (specifically for Xfce since some GTK themes ignore some apps)
### Rhythmbox
cp -f /usr/share/applications/rhythmbox.desktop ~/.local/share/applications/rhythmbox.desktop
sed -i "s/Exec=.*/Exec=env GTK_THEME=Vertex-Dark rhythmbox %U/g" ~/.local/share/applications/rhythmbox.desktop

## Message
echo "
Ctrl + Win + Up/Down/Right/Left tiles your window in 1/2 screen.
Shft + Win + Up/Down/Right/Left tiles your window in 1/4 screen on the top.
Alt  + Win + Up/Down/Right/Left tiles your window in 1/4 screen on the bottom.
Ctrl + Win + Alt shows your window spread & dashboard.
Scroll on the desktop to switch workspaces.
"

fi
# Xfce #

# BASH prompt
chsh -s /bin/bash # Set BASH for the terminal
cp ~/.bashrc ~/.bashrc-vrkbak
## Make the prompt setting like this: # PS1='\[\033[01;32m\][\u@\h\[\033[01;37m\] \[\033[01;34m\]\w\[\033[01;32m\]]\$\[\033[00m\] '
sed -i "s:\\\W:\\\[\\\033[01;34m\\\]\\\w:g" ~/.bashrc

# Configs
sed -i "s/VRK_DESKTOP_SET=.*/VRK_DESKTOP_SET=\"YES\"/g" ~/.vrk/configs/stationinfo

# Finish
echo "Enjoy Vrk Desktop settings. Login again to see them all. :-)
"
sleep 2
