#!/bin/sh
#inkVerbSurfer! verb.ink

# This uploads a local SSH key to a surfer's remote server for user no-password login

# How to use:
## ssh-upload-key [surfer] [SSH_keyname] [server-password] [custom-port (optional)]


GOSURFER=$1
KEYNAME=$2
PASSWORD=$3
NEWPORT=$4

# Check if installed
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check variables
if [ -z $3 ]; then
echo "You need to specify stuff, like this:
ssh-upload-key [surfer] [SSH_keyname] [server-password] [custom-port (optional)]
"
exit 22
fi

# Assign 22 if [custom-port] option is left empty
if [ -z $4 ]; then
NEWPORT=22
fi

# Include the config
. ~/.vrk/go/go.${GOSURFER}.malibu

# Do it all in one command
cat ~/.ssh/${KEYNAME}.pub | ssh -p ${GOPORT} ${GOUSER}@${GOIP} "mkdir -p ~/.ssh && mkdir -p ~/.ssh && cat >>  ~/.ssh/authorized_keys && systemctl reload ssh"
expect "Password:"
send "${PASSWORD}\r"

# Finish
echo "Keys uploaded cap'n. No-password connection ready."

