#!/bin/bash
# This git-updates the current directory, if owned by the user.
## Prerequesite: vgitinst

# How to use:
## vgitpush ["Commit message - optional"] ["Commit long description - optional"]


if [ -n "$1" ]; then
COMMSG=$1
else
COMMSG="Normal vrk station updates"
fi

EXTD_DESCRP=$2

git init
git add .
if [ -n "$2" ]; then
git commit -m "${COMMSG}" -m "${EXTD_DESCRP}" --allow-empty
else
git commit -m "${COMMSG}" --allow-empty
fi
git push -u origin main
